import { Converter, Parameter } from '@intuiface/core';

/**
 * Binding Converter <%= bindingConverterName %>
 */
export class <%= bindingConverterName %> {

    /**
     * Converter entry point used by Intuiface bindings.
     */
    @Converter({
        displayName: '<%= bindingConverterName %>',
        description: 'Example binding converter generated by the Intuiface CDK.'
    })
    public static computeOutput(
        @Parameter({
            name: 'input',
            displayName: 'Input',
            description: 'Value to convert.',
            defaultValue: '',
            type: String
        }) input: string
    ): string
    {
        return input?.toString() ?? '';
    }
}
