name: Bump Version and generate release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest
          default-branch: master
          package-name: intuiface-cdk
          token: ${{secrets.GITHUB_TOKEN}}
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          draft: true
          pull-request-title-pattern: "chore: release ${scope} ${component} ${version}"

      - run: echo "A release was created."
        if: ${{ steps.release.outputs.releases_created }}