name: Bump Version and generate release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          command: manifest
          default-branch: master
          monorepo-tags: false
          package-name: release-please-action
          token: ${{secrets.GITHUB_TOKEN}}
          pull-request-title-pattern: "chore: release ${version}"
          changelog-types: > 
            [{ "type": "feat", "section": "Features", "hidden":false }, 
            { "type": "feature", "section": "Features", "hidden":false }, 
            { "type": "fix", "section": "Bug Fixes", "hidden":false },
            { "type": "perf", "section": "Performance Improvements", "hidden":false },
            { "type": "revert", "section": "Reverts", "hidden":false }, 
            { "type": "docs", "section": "Documentation", "hidden": true }, 
            { "type": "style", "section": "Styles", "hidden": true }, 
            { "type": "chore", "section": "Miscellaneous Chores", "hidden": true }, 
            { "type": "refactor", "section": "Code Refactoring", "hidden": false },
            { "type": "test", "section": "Tests", "hidden": true }, 
            { "type": "build", "section": "Build System", "hidden": true }, 
            { "type": "ci", "section": "Continuous Integration", "hidden": true }]