name: Bump Version and generate release

on:
  push:
    branches:
      - feature/PN-933_PreReleaseCDK

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          command: manifest
          default-branch: feature/PN-933_PreReleaseCDK
          package-name: release-please-action
          token: ${{secrets.GITHUB_TOKEN}}