name: Bump Version and generate release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          command: manifest
          default-branch: master
          monorepo-tags: false
          package-name: release-please-action
          token: ${{secrets.GITHUB_TOKEN}}
          pull-request-title-pattern: "chore: release ${version}"