name: typedoc
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  update-documentation:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name : Install dependencies
        run: npm ci
      - name: Generate docs
        run: npm run docs-all
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'docs(intuiface-cdk): update generated documentation'